[package]
name = "beacon"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.12.1"
thiserror = "2"
rust-ini = "0.21.3"
rayon = "1.11"
memory-stats = "1.2.0"
pretty-bytes = "0.2.2"
nucleo = "0.5.0"
